[package]
name = "zeroed-books-api"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "zeroed-books-api"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.2.2"
async-trait = "0.1.51"
diesel = { version = "1.4.7", features = ["postgres", "uuidv07"] }
diesel_migrations = { version = "1.4.0", features = ["postgres"] }
rand_core = { version = "0.6", features = ["std"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3.22"
uuid = { version = "0.8.2", features = ["serde", "v4"]}

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
default-features = false
features = ["diesel_postgres_pool"]

[dependencies.sendgrid]
version = "0.17.3"
features = ["async"]

[dependencies.tera]
version = "1.12.1"
default-features = false
