services:
    postgres:
        image: postgres:13

        environment:
            POSTGRES_PASSWORD: password

        networks:
            - zeroed-books-api

        volumes:
            - 'postgres-data:/var/lib/postgresql/data'
            - ./init-dev-db.sql:/docker-entrypoint-initdb.d/init.sql

    redis:
        image: redis:6
        networks:
            - zeroed-books-api

networks:
    zeroed-books-api:
        name: zeroed-books-api

volumes:
    postgres-data: null
