services:
    api:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            # Make rocket available outside the container.
            ROCKET_ADDRESS: "0.0.0.0"

        ports:
            - 8000:8000
