services:
    postgres:
        image: postgres:13

        environment:
            POSTGRES_PASSWORD: password

        volumes:
            - 'postgres-data:/var/lib/postgresql/data'
            - ./init-dev-db.sql:/docker-entrypoint-initdb.d/init.sql

    redis:
        image: redis:6

volumes:
    postgres-data: null
