services:
    api:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            DATABASE_URL: postgres://postgres:password@postgres/postgres

        ports:
            - 8000:8000
