services:
    vscode:
        image: mcr.microsoft.com/devcontainers/rust:0-1-bullseye
        environment:
            # Required for the `sqlx` CLI to work.
            DATABASE_URL: postgres://postgres:password@postgres/postgres

        volumes:
            # Mounts the project folder to '/workspace'. While this file is in
            # `.devcontainer`, mounts are relative to the first file in the
            # list, which is a level up.
            - .:/workspace/zeroed-books-api:cached

            # Cache cargo to avoid having to rebuild everything if the container
            # is recreated.
            - cargo-cache:/usr/local/cargo

        # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined

        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
    cargo-cache:
