services:
    vscode:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile

        environment:
            # Required for the `diesel` CLI to work.
            DATABASE_URL: postgres://postgres:password@postgres/postgres

            REDIS_URL: redis://redis

        volumes:
            # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
            # mounts are relative to the first file in the list, which is a level up.
            - .:/workspace:cached

            # Cache GitHub credentials so we don't have to keep
            # re-authenticating.
            - github-credentials:/home/vscode/.config/gh

        # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined

        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
    github-credentials: null
