name: Build

on:
  push:
    branches:
      - main

    # Don't rebuild the Docker image if only the helm chart changed.
    paths-ignore:
      - 'charts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tag
        run: echo "IMAGE_TAG=$(date +%s)-${{ github.sha }}" >> ${GITHUB_ENV}

      - name: Push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            GIT_SHA=${{ github.sha }}
          push: true
          tags: zeroedbooks/api:latest,zeroedbooks/api:${{ env.IMAGE_TAG }}

      # Create a release. The name defaults to the commit hash which is exactly
      # what we want.
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
